// Package main implements `doctor-go`, a fast-path validator for services
// generated by servicectl. It mirrors the Python `servicectl doctor` checks
// in spirit (catch drift from the generated baseline) but is intentionally
// narrow: a single binary, stdlib only, structured JSON output, and a CI
// gate exit code.
//
// Why a separate Go binary?
//
//   - Speed. Cold-start to first result is sub-millisecond on a small repo.
//   - Portability. One static binary, no Python toolchain required.
//   - Polyglot signal. servicectl's core is Python; doctor-go is the
//     Go counterpart that proves the platform stack is multi-language
//     by design, not by accident.
//
// doctor-go is NOT a replacement for `servicectl doctor`. The Python
// doctor is the source of truth and has the full check surface.
// doctor-go is a focused subset suitable for use as a pre-commit or
// tight CI gate where you want fast, structured pass/fail.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// goTestRaceRegex matches a `go test` invocation that includes `-race`,
// in either order (`go test ... -race ...` or `-race ... go test ...`).
// Used by ciUsesGoRace to detect accidental drops of the race detector.
var goTestRaceRegex = regexp.MustCompile(`go\s+test\b[^\n]*-race\b|-race\b[^\n]*go\s+test\b`)

// Severity levels. Mirrors servicectl.doctor.
const (
	SeverityError = "error"
	SeverityWarn  = "warn"
	SeverityInfo  = "info"
)

// Exit codes. Mirrors servicectl.doctor.
const (
	ExitOK    = 0
	ExitWarn  = 1
	ExitError = 2
)

// Check is one rule result. `Passed=false` means the rule fired.
type Check struct {
	Name     string `json:"name"`
	Severity string `json:"severity"`
	Passed   bool   `json:"passed"`
	Message  string `json:"message"`
	Fix      string `json:"fix,omitempty"`
}

// Report aggregates all checks against one service directory.
type Report struct {
	Path         string  `json:"path"`
	DeployTarget string  `json:"deploy_target"`
	ExitCode     int     `json:"exit_code"`
	Summary      Summary `json:"summary"`
	Checks       []Check `json:"checks"`
}

// Summary is the rollup of pass/fail counts by severity.
type Summary struct {
	Passed   int `json:"passed"`
	Errors   int `json:"errors"`
	Warnings int `json:"warnings"`
	Info     int `json:"info"`
}

// Required files that every servicectl-generated service must have,
// regardless of template or deploy target.
var alwaysRequired = []string{
	"Dockerfile",
	".gitignore",
	".gitleaks.toml",
	".env.example",
	"README.md",
}

// azureInfrafiles are required when deploy_target=azure.
var azureInfraFiles = []string{
	"infra/main.bicep",
	"infra/dev.bicepparam",
	"infra/staging.bicepparam",
	"infra/prod.bicepparam",
}

func main() {
	var (
		pathFlag  = flag.String("path", ".", "path to the service directory to validate")
		jsonFlag  = flag.Bool("json", false, "emit JSON instead of human-readable output")
		strict    = flag.Bool("strict", false, "treat warnings as errors (exit 2)")
		showVer   = flag.Bool("version", false, "print version and exit")
	)
	flag.Parse()

	if *showVer {
		fmt.Println("doctor-go v0.1.0")
		return
	}

	abs, err := filepath.Abs(*pathFlag)
	if err != nil {
		fmt.Fprintf(os.Stderr, "doctor-go: cannot resolve path %q: %v\n", *pathFlag, err)
		os.Exit(ExitError)
	}

	report := Validate(abs)
	if *strict && report.Summary.Warnings > 0 {
		// Promote warnings to errors under --strict.
		for i := range report.Checks {
			if report.Checks[i].Severity == SeverityWarn && !report.Checks[i].Passed {
				report.Summary.Warnings--
				report.Summary.Errors++
				report.Checks[i].Severity = SeverityError
			}
		}
		report.ExitCode = report.computeExitCode()
	}

	if *jsonFlag {
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		if err := enc.Encode(report); err != nil {
			fmt.Fprintf(os.Stderr, "doctor-go: json encode failed: %v\n", err)
			os.Exit(ExitError)
		}
	} else {
		writeHuman(os.Stdout, report)
	}

	os.Exit(report.ExitCode)
}

// Validate runs the doctor-go check suite against path and returns a Report.
// Exposed for testing.
func Validate(path string) Report {
	rep := Report{
		Path:         path,
		DeployTarget: inferDeployTarget(path),
		Checks:       []Check{},
	}

	for _, rel := range alwaysRequired {
		rep.Checks = append(rep.Checks, checkFilePresent(path, rel))
	}

	if rep.DeployTarget == "azure" {
		for _, rel := range azureInfraFiles {
			rep.Checks = append(rep.Checks, checkFilePresent(path, rel))
		}
	}

	rep.Checks = append(rep.Checks, checkDockerfileMultiStage(path))
	rep.Checks = append(rep.Checks, checkCIWorkflow(path))
	rep.Checks = append(rep.Checks, checkNoPlaintextSecrets(path))

	// Go-specific checks. Mirror of the Python doctor's _go_checks.
	// Run when the service looks like a Go service (go.mod OR cmd/server/main.go).
	if looksLikeGoService(path) {
		for _, c := range goChecks(path) {
			rep.Checks = append(rep.Checks, c)
		}
	}

	rep.Summary = summarize(rep.Checks)
	rep.ExitCode = rep.computeExitCode()
	return rep
}

func checkFilePresent(root, rel string) Check {
	full := filepath.Join(root, rel)
	if _, err := os.Stat(full); err == nil {
		return Check{
			Name:     "file:" + rel,
			Severity: SeverityError,
			Passed:   true,
			Message:  rel + " — present",
		}
	}
	return Check{
		Name:     "file:" + rel,
		Severity: SeverityError,
		Passed:   false,
		Message:  rel + " — missing",
		Fix:      "regenerate via `servicectl init` or restore the file from source control",
	}
}

func checkDockerfileMultiStage(root string) Check {
	data, err := os.ReadFile(filepath.Join(root, "Dockerfile"))
	if err != nil {
		return Check{
			Name:     "dockerfile:multi-stage",
			Severity: SeverityError,
			Passed:   false,
			Message:  "Dockerfile unreadable or missing",
			Fix:      "ensure Dockerfile is present and readable",
		}
	}
	// Count distinct FROM <image>... AS <name> stages. We scan line-by-line
	// and treat the first FROM case-insensitively, ignoring continuations
	// and comments. This is a coarse check (it doesn't fully parse the
	// Dockerfile grammar), but it's enough to distinguish single-stage from
	// multi-stage builds.
	fromCount := 0
	for _, raw := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(strings.ToUpper(line), "FROM ") {
			fromCount++
		}
	}
	if fromCount >= 2 {
		return Check{
			Name:     "dockerfile:multi-stage",
			Severity: SeverityWarn,
			Passed:   true,
			Message:  fmt.Sprintf("multi-stage Dockerfile detected (%d FROM stages)", fromCount),
		}
	}
	return Check{
		Name:     "dockerfile:multi-stage",
		Severity: SeverityWarn,
		Passed:   false,
		Message:  "Dockerfile is single-stage",
		Fix:      "split build and runtime into separate FROM stages to shrink the final image",
	}
}

func checkCIWorkflow(root string) Check {
	gh := filepath.Join(root, ".github", "workflows", "ci.yml")
	ado := filepath.Join(root, "azure-pipelines.yml")
	hasGH := fileExists(gh)
	hasADO := fileExists(ado)
	if hasGH || hasADO {
		return Check{
			Name:     "ci:workflow",
			Severity: SeverityInfo,
			Passed:   true,
			Message:  fmt.Sprintf("CI workflow present (gh=%v ado=%v)", hasGH, hasADO),
		}
	}
	// No CI workflow is a warning, not an error: some scaffolds use
	// --no-ci intentionally, and CI can also live outside the service
	// repo (monorepo workflows, ops-team-managed pipelines). Treat as
	// drift to investigate, not a hard fail.
	return Check{
		Name:     "ci:workflow",
		Severity: SeverityWarn,
		Passed:   false,
		Message:  "no CI workflow found (.github/workflows/ci.yml or azure-pipelines.yml)",
		Fix:      "add a CI workflow or regenerate via `servicectl init` with --ci=github-actions",
	}
}

func checkNoPlaintextSecrets(root string) Check {
	// Best-effort: scan .env files (NOT .env.example) for likely-secret
	// assignments. This is a coarse check; gitleaks in CI is the real
	// defense. doctor-go's job is to flag the obvious case.
	matches, err := filepath.Glob(filepath.Join(root, ".env"))
	if err != nil || len(matches) == 0 {
		return Check{
			Name:     "secrets:env-file",
			Severity: SeverityInfo,
			Passed:   true,
			Message:  "no .env file present (good — use .env.example as the template)",
		}
	}
	for _, m := range matches {
		data, err := os.ReadFile(m)
		if err != nil {
			continue
		}
		for _, line := range strings.Split(string(data), "\n") {
			trimmed := strings.TrimSpace(line)
			if strings.HasPrefix(trimmed, "#") || trimmed == "" {
				continue
			}
			upper := strings.ToUpper(trimmed)
			if strings.Contains(upper, "PASSWORD=") ||
				strings.Contains(upper, "SECRET=") ||
				strings.Contains(upper, "API_KEY=") ||
				strings.Contains(upper, "TOKEN=") {
				return Check{
					Name:     "secrets:env-file",
					Severity: SeverityError,
					Passed:   false,
					Message:  fmt.Sprintf(".env contains a likely plaintext secret: %s", trimmed),
					Fix:      "move secrets out of .env into your platform's secret store (Key Vault, GitHub Actions secrets, etc.)",
				}
			}
		}
	}
	return Check{
		Name:     "secrets:env-file",
		Severity: SeverityInfo,
		Passed:   true,
		Message:  ".env present but no obvious plaintext-secret patterns",
	}
}

func inferDeployTarget(root string) string {
	if fileExists(filepath.Join(root, "infra", "main.bicep")) {
		return "azure"
	}
	if fileExists(filepath.Join(root, "Dockerfile")) {
		return "local"
	}
	return "unknown"
}

// ---------------------------------------------------------------------------
// Go-specific checks. Mirror of servicectl.doctor._go_checks.
// ---------------------------------------------------------------------------

// looksLikeGoService returns true when the directory has go.mod or the
// conventional cmd/server/main.go entrypoint. Either signal alone means
// "this is a Go-shaped service" and warrants the Go checks.
func looksLikeGoService(root string) bool {
	return fileExists(filepath.Join(root, "go.mod")) ||
		fileExists(filepath.Join(root, "cmd", "server", "main.go"))
}

// goChecks runs the Go-specific doctor checks. Mirrors _go_checks in the
// Python doctor.
func goChecks(root string) []Check {
	var checks []Check

	// go:cmd-server-exists — error if the conventional entrypoint is gone.
	cmdMain := filepath.Join(root, "cmd", "server", "main.go")
	cmdMainExists := fileExists(cmdMain)
	checks = append(checks, Check{
		Name:     "go:cmd-server-exists",
		Severity: SeverityError,
		Passed:   cmdMainExists,
		Message:  ternary(cmdMainExists, "cmd/server/main.go — present", "cmd/server/main.go — missing (the go-webapi scaffold emits this)"),
		Fix:      ternary(cmdMainExists, "", "regenerate with `servicectl init` --template=go-webapi or restore from source control"),
	})

	// go:modfile — error if go.mod is missing entirely.
	gomod := filepath.Join(root, "go.mod")
	modExists := fileExists(gomod)
	checks = append(checks, Check{
		Name:     "go:modfile",
		Severity: SeverityError,
		Passed:   modExists,
		Message:  ternary(modExists, "go.mod — present", "go.mod — missing"),
		Fix:      ternary(modExists, "", "regenerate with `servicectl init` --template=go-webapi"),
	})

	if modExists {
		// go:modfile-go-version — warn if Go version is older than 1.22.
		version, versionOK := readGoModGoVersion(gomod)
		versionPasses := versionOK && parseGoMinor(version) >= 22
		msg := "go.mod has no `go` directive"
		if versionOK {
			msg = "go.mod declares go " + version
		}
		checks = append(checks, Check{
			Name:     "go:modfile-go-version",
			Severity: SeverityWarn,
			Passed:   versionPasses,
			Message:  msg,
			Fix:      ternary(versionPasses, "", "bump `go 1.22` in go.mod to match the scaffold"),
		})

		// go:modfile-module-path — info if module path is empty or still the
		// scaffold's placeholder. We can't tell from the file alone whether
		// the placeholder is intentional (you really are scaffolding a public
		// module) or drift (you forgot to update after forking), so this is
		// info rather than warn.
		module, moduleOK := readGoModModulePath(gomod)
		modulePasses := moduleOK && !strings.Contains(module, "henryorsborn")
		moduleMsg := "no `module` directive in go.mod"
		if moduleOK {
			moduleMsg = "module " + module
		}
		checks = append(checks, Check{
			Name:     "go:modfile-module-path",
			Severity: SeverityInfo,
			Passed:   modulePasses,
			Message:  moduleMsg,
			Fix:      ternary(modulePasses, "", "update the `module` directive in go.mod to your real module path before publishing"),
		})
	}

	// go:has-internal-package — warn if no Go packages live under internal/.
	pkgOK, pkgMsg := hasInternalGoPackage(root)
	checks = append(checks, Check{
		Name:     "go:has-internal-package",
		Severity: SeverityWarn,
		Passed:   pkgOK,
		Message:  pkgMsg,
		Fix:      ternary(pkgOK, "", "add at least one package under `internal/<service>/`"),
	})

	// go:has-tests — warn if no *_test.go files exist anywhere.
	testsOK, testsMsg := hasGoTestFiles(root)
	checks = append(checks, Check{
		Name:     "go:has-tests",
		Severity: SeverityWarn,
		Passed:   testsOK,
		Message:  testsMsg,
		Fix:      ternary(testsOK, "", "add at least one `*_test.go` file (httptest works well for HTTP handlers)"),
	})

	// go:ci-uses-race — info; encourages keeping the race detector on.
	raceOK, raceMsg := ciUsesGoRace(root)
	checks = append(checks, Check{
		Name:     "go:ci-uses-race",
		Severity: SeverityInfo,
		Passed:   raceOK,
		Message:  raceMsg,
		Fix:      ternary(raceOK, "", "add `-race` to `go test` in the CI workflow to catch data races"),
	})

	// go:no-vendor-dir — info; surfaces accidental `go mod vendor` commits.
	noVendorOK, noVendorMsg := hasVendorDir(root)
	checks = append(checks, Check{
		Name:     "go:no-vendor-dir",
		Severity: SeverityInfo,
		Passed:   noVendorOK,
		Message:  noVendorMsg,
		Fix:      ternary(noVendorOK, "", "remove the vendor/ directory if `go mod vendor` was unintentional"),
	})

	return checks
}

// readGoModGoVersion returns the `go` directive value (e.g. "1.22") and true
// on success. Returns "", false when the file is missing or has no go directive.
func readGoModGoVersion(path string) (string, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	for _, raw := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(raw)
		if strings.HasPrefix(line, "go ") && !strings.HasPrefix(line, "go(") {
			parts := strings.Fields(line)
			if len(parts) == 2 {
				return parts[1], true
			}
		}
	}
	return "", false
}

// readGoModModulePath returns the `module` directive value and true on success.
// Returns "", false when the file is missing or has no module directive.
func readGoModModulePath(path string) (string, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	for _, raw := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "//") {
			continue
		}
		if strings.HasPrefix(line, "module ") {
			parts := strings.Fields(line)
			if len(parts) == 2 {
				return parts[1], true
			}
		}
	}
	return "", false
}

// parseGoMinor parses `1.22` or `1.22.0` into the minor version (22).
// Returns 0 on parse failure.
func parseGoMinor(version string) int {
	parts := strings.Split(version, ".")
	if len(parts) < 2 {
		return 0
	}
	n, err := strconv.Atoi(parts[1])
	if err != nil {
		return 0
	}
	return n
}

// hasGoTestFiles returns true if any *_test.go file exists under root.
func hasGoTestFiles(root string) (bool, string) {
	count := 0
	_ = filepath.Walk(root, func(_ string, info os.FileInfo, _ error) error {
		if info == nil || info.IsDir() {
			return nil
		}
		if strings.HasSuffix(info.Name(), "_test.go") {
			count++
		}
		return nil
	})
	if count > 0 {
		return true, fmt.Sprintf("%d *_test.go file(s) found", count)
	}
	return false, "no *_test.go files found"
}

// hasInternalGoPackage returns true if at least one `internal/<name>/*.go`
// package exists.
func hasInternalGoPackage(root string) (bool, string) {
	internal := filepath.Join(root, "internal")
	if !fileExists(internal) {
		return false, "no `internal/` directory"
	}
	entries, err := os.ReadDir(internal)
	if err != nil {
		return false, "`internal/` exists but is unreadable"
	}
	var pkgNames []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		pkgDir := filepath.Join(internal, e.Name())
		matches, _ := filepath.Glob(filepath.Join(pkgDir, "*.go"))
		if len(matches) > 0 {
			pkgNames = append(pkgNames, e.Name())
		}
	}
	if len(pkgNames) > 0 {
		sort.Strings(pkgNames)
		return true, fmt.Sprintf("`internal/` has %d Go package(s): %s", len(pkgNames), strings.Join(pkgNames, ", "))
	}
	return false, "`internal/` exists but contains no Go packages"
}

// ciUsesGoRace returns true if any CI workflow uses `go test ... -race`.
func ciUsesGoRace(root string) (bool, string) {
	candidates := []string{
		filepath.Join(root, ".github", "workflows", "ci.yml"),
		filepath.Join(root, "azure-pipelines.yml"),
	}
	for _, c := range candidates {
		if !fileExists(c) {
			continue
		}
		data, err := os.ReadFile(c)
		if err != nil {
			continue
		}
		text := string(data)
		if goTestRaceRegex.MatchString(text) {
			return true, fmt.Sprintf("`-race` detected in %s", filepath.Base(c))
		}
	}
	return false, "no `-race` flag in `go test` invocations in CI"
}

// hasVendorDir returns true if no `vendor/` directory exists at root.
func hasVendorDir(root string) (bool, string) {
	vendor := filepath.Join(root, "vendor")
	if info, err := os.Stat(vendor); err == nil && info.IsDir() {
		return false, "vendor/ directory present — was `go mod vendor` intentional?"
	}
	return true, "no vendor/ directory (good — modules resolve at build time)"
}

// ternary is a tiny helper to keep check construction readable.
func ternary(cond bool, a, b string) string {
	if cond {
		return a
	}
	return b
}

func summarize(checks []Check) Summary {
	var s Summary
	for _, c := range checks {
		if c.Passed {
			s.Passed++
			continue
		}
		switch c.Severity {
		case SeverityError:
			s.Errors++
		case SeverityWarn:
			s.Warnings++
		case SeverityInfo:
			s.Info++
		}
	}
	return s
}

func (r Report) computeExitCode() int {
	if r.Summary.Errors > 0 {
		return ExitError
	}
	if r.Summary.Warnings > 0 {
		return ExitWarn
	}
	return ExitOK
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

func writeHuman(w *os.File, r Report) {
	fmt.Fprintf(w, "doctor-go: %s  (deploy: %s)\n", r.Path, r.DeployTarget)
	fmt.Fprintln(w, strings.Repeat("=", 60))
	fmt.Fprintln(w)

	if r.Summary.Errors == 0 && r.Summary.Warnings == 0 {
		fmt.Fprintln(w, "all checks passed")
		fmt.Fprintf(w, "\nsummary: %d/%d passed\n", r.Summary.Passed, len(r.Checks))
		return
	}

	if r.Summary.Errors > 0 {
		fmt.Fprintln(w, "ERRORS:")
		for _, c := range r.Checks {
			if !c.Passed && c.Severity == SeverityError {
				fmt.Fprintf(w, "  [✗] FAIL  %s — %s\n", c.Name, c.Message)
				if c.Fix != "" {
					fmt.Fprintf(w, "          fix: %s\n", c.Fix)
				}
			}
		}
		fmt.Fprintln(w)
	}
	if r.Summary.Warnings > 0 {
		fmt.Fprintln(w, "WARNS:")
		for _, c := range r.Checks {
			if !c.Passed && c.Severity == SeverityWarn {
				fmt.Fprintf(w, "  [✗] FAIL  %s — %s\n", c.Name, c.Message)
				if c.Fix != "" {
					fmt.Fprintf(w, "          fix: %s\n", c.Fix)
				}
			}
		}
		fmt.Fprintln(w)
	}

	fmt.Fprintf(w, "summary: %d/%d passed; %d errors, %d warnings, %d info\n",
		r.Summary.Passed, len(r.Checks),
		r.Summary.Errors, r.Summary.Warnings, r.Summary.Info)
}
